function  MOrbit_save(particle, EQLST)
% Save the structure PARTICLE into a MAT file
  %save(['/media/andrea/My Passport Ultra/andrea/Documents/MASTOrbit/EPS2017/ORBIT_' num2str(EQLST.pulseNumber) '_at_' num2str(EQLST.selectedtime, '%1.3f') '_s_' ...
  save(['AAAAAAAAAAAA_ORBIT_' num2str(EQLST.pulseNumber) '_at_' num2str(EQLST.selectedtime, '%1.3f') '_s_' ...
        num2str(particle.initialconditions.energy_eV/1000, '%2.0f') '_keV_' ...
        num2str(180*particle.initialconditions.pitch_angle/pi, '%3.0f') '_deg_' ...
        num2str(180*particle.initialconditions.phi/pi, '%3.0f') '_deg' ... 
        '_R' num2str(particle.orbit.position.R(1), '%1.2f') ...
        '_Z' num2str(particle.orbit.position.z(1), '%1.2f') '.mat'], 'particle');
